-- Inserir 30 versículos bíblicos
INSERT INTO versiculos (frase, referencia) VALUES
('Sede firmes e constantes, sempre abundantes na obra do Senhor, sabendo que o vosso trabalho não é vão no Senhor.', '1 Coríntios 15:58'),
('Não nos cansemos de fazer o bem, porque a seu tempo colheremos, se não desfalecermos.', 'Gálatas 6:9'),
('Tendes necessidade de perseverança, para que, depois de haverdes feito a vontade de Deus, alcanceis a promessa.', 'Hebreus 10:36'),
('Feliz o homem que suporta a provação, porque, depois de ser provado, receberá a coroa da vida.', 'Tiago 1:12'),
('Alegres na esperança, pacientes na tribulação, perseverantes na oração.', 'Romanos 12:12'),
('O Filho do Homem não veio para ser servido, mas para servir e dar a sua vida em resgate por muitos.', 'Mateus 20:28'),
('Se eu, o Senhor e Mestre, vos lavei os pés, também vós deveis lavar os pés uns dos outros.', 'João 13:14-15'),
('Cada um ponha a serviço dos outros o dom que recebeu, como bons administradores da multiforme graça de Deus.', '1 Pedro 4:10'),
('Tudo o que fizerdes, fazei-o de coração, como para o Senhor e não para os homens.', 'Colossenses 3:23-24'),
('Cada um cuide não somente dos seus interesses, mas também dos interesses dos outros. Tende em vós os mesmos sentimentos de Cristo Jesus.', 'Filipenses 2:4-5'),
('Sê forte e corajoso; não temas, nem te apavores, porque o Senhor teu Deus está contigo por onde quer que andares.', 'Josué 1:9'),
('Não temas, porque eu estou contigo; não te assombres, porque eu sou o teu Deus.', 'Isaías 41:10'),
('Deus não nos deu um espírito de covardia, mas de fortaleza, de amor e de moderação.', '2 Timóteo 1:7'),
('O Senhor é minha luz e minha salvação: a quem temerei?', 'Salmo 27:1'),
('No mundo tereis aflições, mas tende coragem: eu venci o mundo.', 'João 16:33'),
('Fazei isto em memória de mim.', 'Lucas 22:19'),
('Eu sou o pão vivo que desceu do céu; quem comer deste pão viverá eternamente.', 'João 6:51'),
('Tomai e comei, isto é o meu corpo... bebei dele todos, porque isto é o meu sangue.', 'Mateus 26:26-28'),
('Todas as vezes que comerdes deste pão e beberdes deste cálice, anunciais a morte do Senhor até que Ele venha.', '1 Coríntios 11:26'),
('Deus não é injusto para se esquecer da vossa obra e do amor que mostrastes para com o seu nome, servindo e perseverando em servir os santos.', 'Hebreus 6:10'),
('Nós amamos porque Ele nos amou primeiro.', '1 João 4:19'),
('Ninguém tem maior amor do que aquele que dá a vida por seus amigos.', 'João 15:13'),
('Sede fervorosos de espírito, servindo ao Senhor.', 'Romanos 12:11'),
('Não vos esqueçais da prática do bem e da partilha, pois tais sacrifícios agradam a Deus.', 'Hebreus 13:16'),
('Todas as vezes que fizestes isso a um destes meus irmãos mais pequeninos, foi a mim que o fizestes.', 'Mateus 25:40'),
('Combati o bom combate, terminei a corrida, guardei a fé. Agora me está reservada a coroa da justiça.', '2 Timóteo 4:7-8'),
('Sê fiel até a morte, e eu te darei a coroa da vida.', 'Apocalipse 2:10'),
('Os que semeiam entre lágrimas recolherão com alegria.', 'Salmo 126:5'),
('Feliz aquele servo que o Senhor, ao chegar, encontrar agindo assim.', 'Mateus 24:46'),
('Fiel é aquele que vos chama; Ele também o fará.', '1 Tessalonicenses 5:24');
